const SchoolSource = {
    EastSikkimSchools: [
        {'schoolId': 37225, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, ASSAM LINGZEY'},
        {'schoolId': 37217, 'schoolName': 'BIRASPATI PARSAI GOVT. SENIOR SECONDARY SCHOOL'},
        {'schoolId': 37352, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, BOJOGHARI'},
        {'schoolId': 37204, 'schoolName': 'TIKALAL NIROULA GOVT. SENIOR SECONDARY SCHOOL, CENTRAL PENDAM'},
        {'schoolId': 37211, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, CHUJACHEN'},
        {'schoolId': 37223, 'schoolName': 'DEORALI GIRLS GOVT. SENIOR SECONDARY SCHOOL'},
        {'schoolId': 37208, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, DIKCHU'},
        {'schoolId': 37219, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, DIKLING'},
        {'schoolId': 37224, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, ENCHEY'},
        {'schoolId': 37202, 'schoolName': 'SONAMATI MEMORIAL GOVT. SENIOR SECONDARY SCHOOL, KHAMDONG'},
        {'schoolId': 37248, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, LINGDOK'},
        {'schoolId': 37280, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, MACHONG'},
        {'schoolId': 37308, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, MAKHA'},
        {'schoolId': 37209, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, MAMRING'},
        {'schoolId': 37220, 'schoolName': 'MODERN GOVT. SENIOR SECONDARY SCHOOL'},
        {'schoolId': 37210, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, RANGPO'},
        {'schoolId': 37206, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, RANKA'},
        {'schoolId': 37213, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, RHENOCK'},
        {'schoolId': 37216, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, RUMTEK'},
        {'schoolId': 37207, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, SAMDONG'},
        {'schoolId': 37214, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, SANG'},
        {'schoolId': 37203, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, SINGTAM'},
        {'schoolId': 37271, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, TADONG'},
        {'schoolId': 37205, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, WEST POINT'},
        {'schoolId': 37290, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, LUING'},
        {'schoolId': 37348, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, ROLEP'},
        {'schoolId': 37373, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, PACHEY'},
        {'schoolId': 37325, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, PABYUIK'},
        {'schoolId': 37289, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, NAMCHEYBONG'},
        {'schoolId': 37326, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, SICHEY'},
        {'schoolId': 37359, 'schoolName': 'GOVT. SENIOR SECONDARY SCHOOL, RORATHANG'},
    ],

    EastSchoolCourseMap: {
        37225: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37217: ['Humanities', 'Commerce', 'Science', 'FP', 'IT'],
        37352: ['Humanities', 'Commerce', 'Science', 'IT', 'RMM'],
        37204: ['Humanities', 'Commerce', 'Science', 'IT', 'RMM'],
        37211: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37223: ['Humanities', 'Commerce', 'Science', 'TTM', 'FP'],
        37208: ['Humanities', 'Commerce', 'IT', 'RMM'],
        37219: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37224: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37202: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37248: ['Humanities', 'Science', 'FP'],
        37280: ['Humanities', 'Commerce', 'Science', 'TTM', 'RMM'],
        37308: ['Humanities', 'Commerce', 'IT','RMM'],
        37209: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37220: ['Humanities', 'TTM', 'RMM'],
        37210: ['Humanities', 'Commerce', 'Science', 'IT', 'RMM'],
        37206: ['Humanities', 'Commerce', 'Science', 'TTM', 'FP'],
        37213: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37216: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37207: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37214: ['Humanities', 'Commerce', 'Science', 'TTM', 'FP'],
        37203: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37271: ['Humanities', 'Commerce', 'Science', 'FP', 'IT'],
        37205: ['Humanities', 'Science', 'IT', 'FP'],
        37290: ['Humanities', 'TTM'],
        37348: ['Humanities', 'IT', 'TTM'],
        37373: ['Humanities', 'IT'],
        37325: ['Humanities', 'IT'],
        37289: ['Humanities', 'IT'],
        37326: ['Humanities', 'RMM'],
        37359: ['Humanities', 'TTM']


    },

    WestSikkimSchool: [
        {'schoolId': 37295, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, YANGSUM'},
        {'schoolId': 37301, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, BERMIOK MARTAM'},
        {'schoolId': 37253, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, KALUK'},
        {'schoolId': 37273, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, SIRIBADAM'},
        {'schoolId': 37251, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, DENTAM'},
        {'schoolId': 37255, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, HEEYANGTHANG'},
        {'schoolId': 37261, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, UTTAREY'},
        {'schoolId': 37250, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, TASHIDINGG'},
        {'schoolId': 37275, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, GERETHANG'},
        {'schoolId': 37336, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, RIBDI'},
        {'schoolId': 37287, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, DARAMDIN'},
        {'schoolId': 37260, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, SOMBARIA'},
        {'schoolId': 37257, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, MANGALBARIA'},
        {'schoolId': 37313, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, KHANSIRBONG'},
        {'schoolId': 37332, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, KAMLINGL'},
        {'schoolId': 37264, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, CHAKUNG'},
        {'schoolId': 37331, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, GELLING'},
        {'schoolId': 37249, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, YUKSAM'},
        {'schoolId': 37263, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, KHECHUPERI'},
        {'schoolId': 37256, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, SORENG'},
        {'schoolId': 37262, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, BURIAKHOP'},
        {'schoolId': 37258, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, THARPU'},
        {'schoolId': 37378, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, CHOTASAMDUNG'},
        {'schoolId': 37292, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, SAKYONG'},
        {'schoolId': 37302, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, DARAP'},
        {'schoolId': 37254, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, LINGCHOM'},
        {'schoolId': 37344, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, LEGSHIP'},
        {'schoolId': 37269, 'schoolName': 'GOVERNMENT GIRLS SENIOR SECONDARY SCHOOL, GYALSHING'},
        {'schoolId': 37252, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, PELLING'},
    ],

    WestSchoolCourseMap: {
        37295: ['Humanities','IT'],
        37301: ['Humanities', 'TTM'],
        37253: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37273: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37251: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37255: ['Humanities', 'Commerce', 'Science', 'TTM', 'RMM'],
        37261: ['Humanities', 'Commerce', 'IT', 'TTM'],
        37250: ['Humanities', 'Science', 'TTM', 'FP'],
        37275: ['Humanities', 'IT'],
        37336: ['Humanities', 'IT'],
        37287: ['Humanities', 'Commerce', 'TTM', 'IT'],
        37260: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37257: ['Humanities', 'Commerce', 'Science','TTM','IT'],
        37313: ['Humanities', 'TTM'],
        37332: ['Humanities', 'IT'],
        37264: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37331: ['Humanities', 'IT'],
        37249: ['Humanities', 'Commerce', 'TTM', 'IT'],
        37263: ['Humanities', 'TTM', 'IT'],
        37256: ['Humanities', 'Commerce', 'Science', 'FP', 'IT'],
        37262: ['Humanities', 'Commerce', 'Science', 'TTM', 'RMM'],
        37258: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37378: ['Humanities', 'TTM'],
        37292: ['Humanities', 'IT', 'Commerce'],
        37302: ['Humanities', 'Science', 'TTM', 'IT'],
        37254: ['Humanities', 'IT', 'TTM'],
        37344: ['Humanities', 'Commerce', 'RMM', 'IT'],
        37269: ['Humanities', 'Commerce', 'Science', 'TTM', 'IT'],
        37252: ['Humanities', 'Commerce', 'Science', 'FP', 'IT'],

    },
    SouthSikkimSchool: [
        {'schoolId': 37240, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, BERMIOK TOKAL'},
        {'schoolId': 37243, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, RAVANGLA'},
        {'schoolId': 37247, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, LINGMOO'},
        {'schoolId': 37233, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, NAMCHI'},
        {'schoolId': 37235, 'schoolName': 'GOVERNMENT GIRLS SENIOR SECONDARY SCHOOL, NAMCHI'},
        {'schoolId': 37245, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, NAMTHANG'},
        {'schoolId': 37234, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, SADAM'},
        {'schoolId': 37242, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, TEMI'},
        {'schoolId': 37241, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, JORETHANG'},
        {'schoolId': 37244, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, YANGYANG'},
        {'schoolId': 37232, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, LINGEE'},
        {'schoolId': 37246, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, NANDUGAON'},
        {'schoolId': 37276, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, PERBING'},
        {'schoolId': 37306, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, RATEYPANI'},
        {'schoolId': 37215, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, KEWZING'},
        {'schoolId': 37239, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, SUMBUK'},
        {'schoolId': 37267, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, KITAM'},
        {'schoolId': 37320, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, BEN'},
        {'schoolId': 37238, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, NTL VOK'},
        {'schoolId': 37268, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, MELLI GUMPA'},
        {'schoolId': 37284, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, MELLI BAZAR'},
        {'schoolId': 37237, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, BIKMAT'}
    ],

    SouthSchoolCourseMap: {
        37240: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37243: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37247: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37233: ['Humanities', 'Commerce', 'Science', 'TTM','RMM'],
        37235: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37245: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37234: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37242: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37241: ['Humanities', 'Commerce', 'Science', 'IT', 'RMM'],
        37244: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37232: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37246: ['Humanities', 'Science','IT','TTM'],
        37276: ['Humanities', 'IT', 'TTM'],
        37306: ['Humanities', 'IT','TTM'],
        37215: ['Humanities', 'IT','TTM'],
        37239: ['Humanities', 'IT','TTM'],
        37267: ['Humanities', 'RMM','TTM'],
        37320: ['Humanities','IT'],
        37238: ['Humanities','IT'],
        37268: ['Humanities','IT'],
        37284: ['Humanities','IT'],
        37237: ['Humanities','IT'],

    },
    NorthSikkimSchool: [
        {'schoolId': 37228, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, MANGAN'},
        {'schoolId': 37227, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, HEEGYATHANG'},
        {'schoolId': 37231, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, PHODONG'},
        {'schoolId': 37317, 'schoolName': 'GOVT SENIOR SECONDARY SCHOOL, KABI'},
        {'schoolId': 37274, 'schoolName': 'GOVERNMENT SENIOR SECONDARY SCHOOL, MANGHSHILLA'},
        {'schoolId': 37226, 'schoolName': 'TT GOVERNMENT SENIOR SECONDARY SCHOOL, CHUNGTHANG'},

    ],
    NothSchoolCourseMap: {
        37228: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37227: ['Humanities', 'Commerce', 'Science', 'IT', 'TTM'],
        37231: ['Humanities', 'Commerce', 'Science', 'IT', 'FP'],
        37317: ['Humanities', 'TTM', 'IT'],
        37274: ['Humanities', 'TTM', 'IT'],
        37226: ['Humanities', 'TTM']

   },
    College: [
        {'collegeId': 1000, 'collegeName': 'CENTRE FOR COMPUTERS AND COMMUNICATION TECHNOLOGY, CHISOPANI'},
        {'collegeId': 1001, 'collegeName': 'ADVANCED TECHNICAL TRAINING CENTRE, BARDANG'},
        ],
    CollegeCourseMap: {
        1000: [
            'Diploma in Computer Science and Technology',
            'Diploma in Civil Engineering',
            'Diploma in Electrical and Electronics',
            'Diploma in Electronics and Communication Engineering',
            'Diploma in Mechanical Engineering'
        ],
        1001: [
            'Diploma in Mechanical Engineering',
            'Diploma in Computer Engineering',
            'Diploma in Mechatronics',
            'Diploma in Manufacturing Technology',
            'Diploma in Civil Engineering'
        ],
    },
}
export default SchoolSource;



